server:
  port: 8082

spring:
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  application:
    name: resource-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yhh_game_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto

knife4j:
  enable: true
  setting:
    language: zh-CN

# 文件上传配置
upload:
  # 文件上传根路径
  path: D:/yhh_game/uploads
  # 允许上传的文件类型
  allowed-types: image/jpeg,image/png,image/gif,image/webp
  # 访问URL前缀
  url-prefix: /uploads/
