spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type
            maxAge: 3600
      routes:
        - id: user-route
          predicates:
            - Path=/user/**
          uri: lb://user-service
          order: 1

        - id: resource-route
          predicates:
            - Path=/resource/**
          uri: lb://resource-service
          order: 2

